variables:
  DOCKER_IMAGE_NAME: brunosouzapicinini/curso-alura-react
  VERSION: latest

stages:
  - compile
  - build

compile-test:
  stage: compile
  image: node:14.8.0-buster
  script:
    - npm install
    - npm run build

get-build-version:
  stage: compile
  image: node:14.8.0-buster
  script:
    - echo "VERSION=$(node -p "require('./package.json').version")" >> build.env
  artifacts:
    reports:
      dotenv: build.env

build-docker:
  stage: build
  image: docker:stable
  services:
  - docker:dind
  before_script:
    - docker login -u $DOCKER_REPO_USER -p $DOCKER_REPO_PASS
  script:
    - echo $DOCKER_IMAGE_NAME
    - echo $VERSION
    - docker build -t $DOCKER_IMAGE_NAME:$VERSION .
    - docker image push $DOCKER_IMAGE_NAME:$VERSION
  dependencies:
    - get-build-version
