variables:
  DOCKER_REPO_NAME: https://hub.docker.com/
  DOCKER_IMAGE_NAME:  brunosouzapicinini/curso-alura-react

stages:
  - compile
  - build

compile-test:
  stage: compile
  image:
    name: node:14.17.3-buster
  script:
    - npm install
    - npm run build

build-docker:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login $DOCKER_REPO_NAME -u $DOCKER_REPO_USER -p $DOCKER_REPO_PASS
  script:
    - docker build -t $DOCKER_IMAGE_NAME:${versao} .
    - docker image push $DOCKER_IMAGE_NAME:${versao}