variables:
  DOCKER_IMAGE_NAME: brunosouzapicinini/curso-alura-react
  PACKAGE_VERSION: 

stages:
  - compile
  - build

compile-test:
  variables: 
    PACKAGE_VERSION: (cat package.json \ | grep version \| head -1 \| awk -F: '{ print $2 }' \ | sed 's/[",]//g' | tr -d '[[:space:]]')
  stage: compile
  image: node:14.8.0-buster
  script:
    - npm install
    - npm run build
  
build-docker:
  stage: build
  image: docker:stable
  services:
  - docker:dind
  before_script:
    - docker login -u $DOCKER_REPO_USER -p $DOCKER_REPO_PASS
  script:
    - docker build -t $DOCKER_IMAGE_NAME:$PACKAGE_VERSION .
    - docker image push $DOCKER_IMAGE_NAME:$PACKAGE_VERSION