variables:
  DOCKER_IMAGE_NAME: brunosouzapicinini/curso-alura-react

stages:
  - compile
  - build

compile-test:
  stage: compile
  image: node:14.8.0-buster
  script:
    - npm install
    - npm run build
  
build-docker:
  stage: build
  image: docker:stable
  services:
  - docker:dind
  before_script:
    - apt-get update && apt-get install -yqq jq
    - export VERSION=$(jq -r .version package.json)
    - docker login -u $DOCKER_REPO_USER -p $DOCKER_REPO_PASS
  script:
    - docker build -t $DOCKER_IMAGE_NAME:$VERSION .
    - docker image push $DOCKER_IMAGE_NAME:$VERSION
